### ISSUE TITLE
I set currentState by db, then how should I use for transition?

### ISSUE THREAD

**Issue by lehug** [j-easy/easy-states#10]
FiniteStateMachineImpl.currentState is set by constructor, and do not have a currentState set method. Then I set currentState by db, then how should I use for transition? Thanks

**Comment by lehug** [comment]
create many FiniteStateMachine? the initialState is not the full FSM initialState?

**Comment by fmbenhassine** [comment]
If you decide to use a finite state machine, you should **not** set its state manually (otherwise I don't see the added value of using a FSM over a simple variable that could be set manually).

With a FSM, you define the start/end state(s) and the transitions between them and let the FSM decide to which state it should move next based on the event that occurred. You should not be setting the current FSM state manually.
